services:
  - type: web
    name: livebetiq-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production